frase = 'Curso em Vídeo Python'
print(frase)
print(frase[3])
print(frase[1:15:2])
print(frase[::])
print(frase[5:])
#print("""Welcome! It's my programmes made in Python for practice.
#I'm a new programmer and I'm trying to get better in programming""")
print(frase.upper().count('o'))
#print(len(frase))
print(frase.strip())
print(frase.replace('Python' , 'Android'))
print('Curso' in frase)
print(frase.find('Vídeo'))
dividido=frase.split()
print(dividido)