c=input('digite algo: ')
print(type(c))
print('o tipo de c é numérico: ', c.isnumeric())
print('o tipo de c é alpha: ', c.isalpha())
print('o tipo de c é upper: ', c.isupper())
print('o tipo de c é lower: ', c.islower())
print('o tipo de c é alphanum: ', c.isalnum())
print('o tipo de c é ascii: ', c.isascii())
print('o tipo de c é decimal: ', c.isdecimal())
#print('o tipo de c é capitalizada:', c.istitle())
print('o tipo de c é : {}'.format(c.istitle()))
